import Head from 'next/head'
import {useQuery} from '@tanstack/react-query'
import {getData} from "@/utils/getData";
import {useRouter} from "next/router";
import Heading from "@/components/Shared/Heading";
import {Key} from "react";
import Link from "next/link";

export default function Home() {
   const router = useRouter()
   const {slug} = router.query

   const {data, isLoading, isError} = useQuery({queryKey: [slug], queryFn: () => getData(`/motorcycles`)})

   if (isLoading) {
      return <div>Loading...</div>
   }

   if (isError) {
      return <div>Error...</div>
   }

   const motorcycles = data.data;
   console.log(motorcycles)

   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta
               name="description"
               content="Generated by create next app"
            />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link
               rel="icon"
               href="/favicon.ico"
            />
         </Head>

         <Heading heading={"Nasze motocykle - DEMO"}/>
         <ul style={{margin: "6em 0", marginBottom: "50vh"}}>
            {motorcycles.map((motorcycle: { attributes: { id: string, slug: string, name: string } }) => {
               return (
                  <li key={motorcycle.attributes.id} style={{margin: "2em 0"}}>
                     <Link href={"/motocykle/" + motorcycle.attributes.slug}>
                        <p>{motorcycle.attributes.name}</p>
                     </Link>
                  </li>
               )
            })}
         </ul>
      </>
   )
}
