import Head from 'next/head'
import {useQuery} from '@tanstack/react-query'
import {getData} from "@/utils/getData";
import Hero from "@/components/Home/Hero";
import About from "@/components/Home/About";
import ServiceStages from "@/components/Home/ServiceStages";
import Faq from "@/components/Shared/FAQ";

export default function Home() {
   const {data, isLoading, isError} = useQuery({queryKey: ['home'], queryFn: () => getData("/home")})

   if (isLoading) {
      return <div>Loading...</div>
   }

   const {
      heroComponent,
      serviceStageComponent,
      aboutUsComponent,
      faqComponent
   } = data.data.attributes;
   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta
               name="description"
               content="Generated by create next app"
            />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link
               rel="icon"
               href="/favicon.ico"
            />
         </Head>
         <Hero content={heroComponent}/>
         <ServiceStages content={serviceStageComponent}/>
         <About content={aboutUsComponent}/>
         <Faq content={faqComponent}/>
      </>
   )
}
