import Head from 'next/head'
import {useEffect} from 'react'
import axios from '@/config/axios'
import {useQuery} from '@tanstack/react-query'
import {getData} from "@/utils/getData";


export default function Home() {
   const {data, isLoading, isError} = useQuery({queryKey: ['home'], queryFn: () => getData("/home")})
   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta
               name="description"
               content="Generated by create next app"
            />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link
               rel="icon"
               href="/favicon.ico"
            />
         </Head>
         <p>123</p>
      </>
   )
}
